DROP USER IF EXISTS 'u_royaume_du_hibou'@'%';
CREATE USER 'u_royaume_du_hibou'@'%' IDENTIFIED BY 'vlKuOZC0LKnvLHAD';
GRANT USAGE ON *.* TO 'u_royaume_du_hibou'@'%' IDENTIFIED BY 'vlKuOZC0LKnvLHAD' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
GRANT SELECT, INSERT, UPDATE, DELETE ON royaume_du_hibou.* TO 'u_royaume_du_hibou'@'%';